import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db/prisma';
import { requireAuth } from '@/lib/auth/middleware';

function ser(s: any) {
  return {
    ...s,
    _id: String(s.id),
    date: s.date?.toISOString(),
    balance:        s.balance        ?? 0,
    remark:         s.remark         ?? '',
    sourceType:     s.sourceType     ?? 'manual',
    isAutoGenerated: s.isAutoGenerated ?? false,
    bankAccount: s.bankAccount ? { ...s.bankAccount, _id: String(s.bankAccount.id) } : null,
  };
}

export async function GET(req: NextRequest) {
  const { error } = await requireAuth(['admin', 'accountant']);
  if (error) return error;

  const sp            = req.nextUrl.searchParams;
  const bankAccountId = sp.get('bankAccount');
  const period        = sp.get('period') || 'month';
  const month         = sp.get('month') ? parseInt(sp.get('month')!) : null;
  const year          = sp.get('year')  ? parseInt(sp.get('year')!)  : null;
  const date          = sp.get('date')  || '';
  const rangeStart    = sp.get('start') || '';
  const rangeEnd      = sp.get('end')   || '';

  const where: any = {};
  if (bankAccountId) where.bankAccountId = parseInt(bankAccountId);

  if (period === 'month' && month && year) {
    where.date = { gte: new Date(year, month - 1, 1), lte: new Date(year, month, 0, 23, 59, 59, 999) };
  } else if (period === 'day' && date) {
    const d = new Date(date);
    where.date = {
      gte: new Date(d.getFullYear(), d.getMonth(), d.getDate(), 0, 0, 0),
      lte: new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999),
    };
  } else if (period === 'range' && rangeStart && rangeEnd) {
    const s = new Date(rangeStart); const e = new Date(rangeEnd);
    where.date = {
      gte: new Date(s.getFullYear(), s.getMonth(), s.getDate(), 0, 0, 0),
      lte: new Date(e.getFullYear(), e.getMonth(), e.getDate(), 23, 59, 59, 999),
    };
  }
  // period === 'all' → no date filter

  try {
    const statements = await prisma.bankStatement.findMany({
      where, orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
      include: { bankAccount: { select: { id: true, bankName: true, accountNumber: true } } },
    });
    return NextResponse.json({ statements: statements.map(ser) });
  } catch (err: any) {
    // If new columns don't exist yet (db:push not run), fall back to basic query
    console.error('Bank statements query error:', err.message);
    try {
      const statements = await prisma.$queryRaw`
        SELECT bs.id, bs.date, bs.transactionId, bs.creditAmount, bs.debitAmount,
               bs.description, bs.createdBy, bs.createdAt,
               ba.id as ba_id, ba.bankName, ba.accountNumber
        FROM bank_statements bs
        LEFT JOIN bank_accounts ba ON bs.bankAccountId = ba.id
        ${bankAccountId ? prisma.$queryRaw`WHERE bs.bankAccountId = ${parseInt(bankAccountId)}` : prisma.$queryRaw``}
        ORDER BY bs.date ASC
      ` as any[];

      const mapped = (statements as any[]).map(s => ({
        _id: String(s.id), id: s.id,
        date: s.date?.toISOString?.() || s.date,
        transactionId: s.transactionId || '',
        creditAmount: s.creditAmount || 0,
        debitAmount: s.debitAmount || 0,
        balance: 0, remark: '', sourceType: 'manual', isAutoGenerated: false,
        description: s.description || '',
        bankAccount: s.ba_id ? { _id: String(s.ba_id), id: s.ba_id, bankName: s.bankName, accountNumber: s.accountNumber } : null,
      }));
      return NextResponse.json({ statements: mapped, warning: 'Run npm run db:push to enable full features' });
    } catch (fallbackErr: any) {
      return NextResponse.json({ statements: [], error: 'Database needs migration. Run: npm run db:push' });
    }
  }
}

export async function POST(req: NextRequest) {
  const { error, session } = await requireAuth(['admin', 'accountant']);
  if (error) return error;
  const body = await req.json();
  const { date, transactionId, creditAmount, debitAmount, bankAccount, description, remark, balance } = body;

  if (!bankAccount)
    return NextResponse.json({ error: 'Bank account is required' }, { status: 400 });
  if (!description?.trim())
    return NextResponse.json({ error: 'Description is required' }, { status: 400 });

  const credit = parseFloat(creditAmount || '0');
  const debit  = parseFloat(debitAmount  || '0');

  try {
    // Try with new fields first
    const lastEntry = await prisma.bankStatement.findFirst({
      where: { bankAccountId: parseInt(bankAccount) },
      orderBy: { date: 'desc' },
      select: { balance: true },
    });
    const lastBalance = (lastEntry as any)?.balance || 0;
    const runningBalance = parseFloat(balance || '0') || (lastBalance + credit - debit);

    const statement = await prisma.bankStatement.create({
      data: {
        date: date ? new Date(date) : new Date(),
        transactionId: transactionId || '',
        creditAmount: credit, debitAmount: debit,
        balance: runningBalance,
        bankAccountId: parseInt(bankAccount),
        description: description.trim(),
        remark: remark || '',
        sourceType: 'manual',
        isAutoGenerated: false,
        createdBy: parseInt((session!.user as any).id),
      },
      include: { bankAccount: { select: { id: true, bankName: true, accountNumber: true } } },
    });

    await prisma.bankAccount.update({
      where: { id: parseInt(bankAccount) },
      data: { currentBalance: { increment: credit - debit } },
    });

    return NextResponse.json({ statement: ser(statement) }, { status: 201 });

  } catch (err: any) {
    // Fallback for old schema (before db:push)
    try {
      const statement = await prisma.bankStatement.create({
        data: {
          date: date ? new Date(date) : new Date(),
          transactionId: transactionId || '',
          creditAmount: credit, debitAmount: debit,
          bankAccountId: parseInt(bankAccount),
          description: description.trim(),
          createdBy: parseInt((session!.user as any).id),
        } as any,
      });

      await prisma.bankAccount.update({
        where: { id: parseInt(bankAccount) },
        data: { currentBalance: { increment: credit - debit } },
      });

      return NextResponse.json({ statement: { ...statement, _id: String(statement.id), balance: 0, remark: '', sourceType: 'manual' } }, { status: 201 });
    } catch (fallbackErr: any) {
      return NextResponse.json({ error: 'Database needs migration. Run: npm run db:push' }, { status: 500 });
    }
  }
}
