import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db/prisma';
import { requireAuth } from '@/lib/auth/middleware';

export async function POST(req: NextRequest) {
  const { error, session } = await requireAuth(['admin', 'accountant']);
  if (error) return error;

  const { bankAccountId, month, year } = await req.json();
  if (!bankAccountId || !month || !year)
    return NextResponse.json({ error: 'bankAccountId, month, year required' }, { status: 400 });

  const userId = parseInt((session!.user as any).id);

  // Check if new columns exist
  try {
    await prisma.bankStatement.findFirst({ select: { balance: true, remark: true, sourceType: true, isAutoGenerated: true } });
  } catch {
    return NextResponse.json({ error: 'Database needs migration first. Run: npm run db:push then try again.' }, { status: 500 });
  }

  const start = new Date(year, month - 1, 1);
  const end   = new Date(year, month, 0, 23, 59, 59, 999);
  const bId   = parseInt(bankAccountId);

  // Delete existing AUTO-GENERATED entries for this account+month (regenerate fresh)
  await prisma.bankStatement.deleteMany({
    where: { bankAccountId: bId, isAutoGenerated: true, date: { gte: start, lte: end } },
  });

  type Entry = {
    date: Date; credit: number; debit: number;
    description: string; remark: string;
    transactionId: string; sourceType: string; sourceId: number;
  };
  const entries: Entry[] = [];

  // ── 1. Verified TRADER payments (money received INTO this bank account) ──
  // Include ALL verified trader payments for this account (bankAccountId = bId OR null for cash)
  // Trader pays US — this is a CREDIT to our bank
  const traderPayments = await prisma.payment.findMany({
    where: {
      status: 'verified',
      paymentFor: 'trader',
      date: { gte: start, lte: end },
      // Include payments linked to this bank account OR cash payments (no bank account)
      OR: [
        { bankAccountId: bId },
        { bankAccountId: null, paymentMethod: 'Cash' },
      ],
    },
    include: { trader: { select: { name: true } } },
  });
  for (const p of traderPayments) {
    entries.push({
      date: p.date, credit: p.amount, debit: 0,
      description: `Payment received from trader`,
      remark: `Received from: ${p.trader?.name || 'Trader'}`,
      transactionId: p.utrNumber || p.chequeNumber || p.transactionId || '',
      sourceType: 'payment_trader', sourceId: p.id,
    });
  }

  // ── 2. Verified COMPANY payments (we paid the company — DEBIT from our bank) ──
  const companyPayments = await prisma.payment.findMany({
    where: {
      status: 'verified',
      paymentFor: 'company',
      bankAccountId: bId,
      date: { gte: start, lte: end },
    },
    include: { company: { select: { name: true } } },
  });
  for (const p of companyPayments) {
    entries.push({
      date: p.date, credit: 0, debit: p.amount,
      description: `Payment made to company`,
      remark: `Paid to: ${p.company?.name || 'Company'}`,
      transactionId: p.utrNumber || p.chequeNumber || p.transactionId || '',
      sourceType: 'payment_company', sourceId: p.id,
    });
  }

  // ── 3. Expenses debited from this bank account ──
  const expenses = await prisma.expense.findMany({
    where: { bankAccountId: bId, date: { gte: start, lte: end } },
  });
  for (const e of expenses) {
    entries.push({
      date: e.date, credit: 0, debit: e.amount,
      description: `Expense: ${e.expenseType}`,
      remark: `Expense Type: ${e.expenseType}`,
      transactionId: e.transactionId || '',
      sourceType: 'expense', sourceId: e.id,
    });
  }

  // Sort by date ascending
  entries.sort((a, b) => a.date.getTime() - b.date.getTime());

  // Opening balance = last balance before this period (manual entries only)
  const prevEntry = await prisma.bankStatement.findFirst({
    where: { bankAccountId: bId, date: { lt: start }, isAutoGenerated: false },
    orderBy: { date: 'desc' },
    select: { balance: true },
  });
  let runningBalance = (prevEntry as any)?.balance || 0;

  // Create all auto-generated entries
  const created = [];
  for (const e of entries) {
    runningBalance = runningBalance + e.credit - e.debit;
    const stmt = await prisma.bankStatement.create({
      data: {
        date: e.date, transactionId: e.transactionId,
        creditAmount: e.credit, debitAmount: e.debit, balance: runningBalance,
        bankAccountId: bId, description: e.description,
        remark: e.remark, sourceType: e.sourceType,
        sourceId: e.sourceId, isAutoGenerated: true,
        createdBy: userId,
      },
    });
    created.push(stmt);
  }

  return NextResponse.json({
    message: `Generated ${created.length} entries for ${new Date(year, month - 1).toLocaleString('en-IN', { month: 'long', year: 'numeric' })}`,
    count: created.length,
  });
}
